### ISSUE TITLE
model directive not working for checkbox, radio buttons, and select

### ISSUE THREAD

**Issue by mrez0** [ujjwalguptaofficial/mahal#11]
## Summary

"**model**" directive to be improved to include two-way data binding with different HTML elements such as checkbox, select, textarea.

**Comment by ujjwalguptaofficial** [comment]
Thanks for adding the issue @mrez0, will work on it.

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 1.8.1 @mrez0 , please check and let me know.

**Comment by ujjwalguptaofficial** [comment]
have also updated doc - https://mahaljs.com/docs/basic/model/#checkbox

**Comment by mrez0** [comment]
Thanks @ujjwalguptaofficial for the updates.

Works great for checkbox, radio buttons, and textarea.

For **"select"** the binding is working from HTML to JS, but not the other way from JS to HTMl.
For example, when "select" is bound to a string in the component class, it does not show the correct option in the select element.
Also, when changing the select value in JS code, it does not reflect that value to the select element in HTML.

Another issue _(I don't know if I need to open another issue for that or not)_ is that the command "npx @mahaljs/creator init" shall install the last updated version of the framework. Currently, it is installing the framework @version 1.5.0

**Comment by ujjwalguptaofficial** [comment]
oh forgot to handle the select, handled in v - 1.8.2. Please check and let me know.

> also regarding the latest version in `mahal-creator` - this has been done deliberately to not to update to latest version as things might not be stable in each version - i am keeping the package stable in the creator.

**Comment by mrez0** [comment]
All works perfectly. Thanks
