### ISSUE TITLE
Expressions in if

### ISSUE THREAD

**Issue by djpate** [ujjwalguptaofficial/mahal#3]
# Title 

Not able to use expressions in the `if` directive

# Description 

I'm not sure if that's supposed to work but I was expecting to be able to do

```<span :if(tasks.length)>You have pending tasks</span>```
or
```<span :if(tasks.length > 0)>You have pending tasks</span>```

I have to write a computed method that does that in the class which is fine if that's by design but I wasn't sure.

**Comment by ujjwalguptaofficial** [comment]
Yes, you are right - its better to use `Computed`. We could support them but it will make codes nasty and unreadable.  The mahal frameworks wants you to write clean code as much as possible.

**Comment by ujjwalguptaofficial** [comment]
got your point. I will consider these in future roadmap or atleast better error message  so that user knows what to do. Thank you very much for your suggestion.

**Comment by ujjwalguptaofficial** [comment]
@djpate i have fixed some of the issues, now should supports all type of expression. Let me know if you find any bug.

i have fixed in `mahal-html-compiler` with version - 1.1.4. You need to update the `mahal-html-compiler`.
