### ISSUE TITLE
Improving the UI of the Mahal.js Library Website

### ISSUE THREAD

**Issue by Subhampreet** [ujjwalguptaofficial/mahal#9]
## Summary

Hi Ujjwal 👋,

First of all Congratulations on bringing out this awesome idea into reality. I would like to suggest to improvise the UI of the Website for the Mahal.js. Currently the UI is a generic one, I would like to work on the design improvements for your website using trending UI principles. 

### Basic example

I am quite good at improvising the pre-existing websites. Some of the examples of my work are as follows:

https://instagram-clone-react-70113.web.app/

Similarly I would like to improve component by component for your website as well. 

### Motivation

Since the concept is quite unique one, I really look forward to contribute to such a great idea 🎉!

**Comment by Subhampreet** [comment]
Hi @ujjwalguptaofficial ,

Thanks for your Response!!!

I will be more than glad to help you with creating better UI and team up with you on your future plans as well. I will ping you on LinkedIn and we can have a more detailed discussion over there. 

Thanks 🎉!!!

**Comment by ujjwalguptaofficial** [comment]
closing for now, will reopen later.
